name: the_algorithms_dart

repository: https://github.com/TheAlgorithms/Dart

dependencies:
  test: ^1.15.4
  coverage: ^0.14.1

dev_dependencies:
  stack: ^0.2.0

environment:
  sdk: ">=2.10.0 <3.0.0"
